export enum TypeService {
    ABONNEMENT_WIFI = 'ABONNEMENT_WIFI',
    ABONNEMENT_MOBILE = 'ABONNEMENT_MOBILE',
    DON = 'DON',
    FACTURE_EAU = 'FACTURE_EAU',
    FACTURE_ELECTRICITE = 'FACTURE_ELECTRICITE',
    RECHARGE = 'RECHARGE'
}